stages:
  - build
  - deploy

variables:
  SERVICES_INFO_ENDPOINT: https://s3.amazonaws.com/offcourse-services-info-global
  PLATFORM_ENDPOINT: offcourse.io
  SERVICES_INFO_FILE: services-info.json
  SERVICES_INFO_BUCKET: s3://offcourse-services-info-global
  REGISTRY: registry.gitlab.com

.build_template: &build_definition
  stage: build 
  image: ${REGISTRY}/offcourse/hugo-container:latest
  script:
    - hugo -D
  artifacts:
    paths:
      - public/

build:
  <<: *build_definition
  only:
    - master

.deploy_template: &deploy_definition
  stage: deploy
  image: ${REGISTRY}/offcourse/aws-container:latest
  script:
    - curl ${SERVICES_INFO_ENDPOINT}/global.json > ${SERVICES_INFO_FILE} 
    - BUCKET=$(cat ${SERVICES_INFO_FILE} | jq '.["pitchdeck"]["bucket_name"]')
    - BUCKET="${BUCKET%\"}" && BUCKET="${BUCKET#\"}"
    - echo $BUCKET
    - aws s3 sync public "s3://${BUCKET}"

deploy:
  <<: *deploy_definition
  environment:
    name: investors
    url: https://pitchdeck.${PLATFORM_ENDPOINT}
  dependencies:
    - build
  only:
    - master
